services:
  mcp-server:
    container_name: mcp-server
    build:
      context: ./mcp-server
    ports:
      - "9090:9090"
    env_file:
      - ./mcp-server/.env
    networks:
      - agent-network
    environment:
    # https://huggingface.co/docs/huggingface_hub/en/package_reference/environment_variables#xdgcachehome
      - HF_HOME=/root/.cache/huggingface
    volumes:
      - ./.vscode:/app/.vscode
      - ./videos:/app/videos
      - ~/.cache:/root/.cache
      - ~/.cache/huggingface:/root/.cache/huggingface
  agent-api:
    container_name: agent-api
    build:
      context: ./agent-api
    ports:
      - "8080:8080"
    environment:
      - DISABLE_NEST_ASYNCIO=True
    env_file:
      - ./agent-api/.env
    networks:
      - agent-network
    depends_on:
      - mcp-server
    volumes:
      - ./videos:/app/videos
      - ./.vscode:/app/.vscode
  # ui:
  #   container_name: ui
  #   build:
  #     context: ./ui
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8501:8501"
  #   depends_on:
  #     - agent-api
  #     - mcp-server
  #   networks:
  #     - agent-network
  #   volumes:
  #     - ./videos:/app/videos
  kubrick-ui:
    container_name: kubrick-ui
    build:
      context: ./kubrick-ui
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - agent-api
      - mcp-server
    networks:
      - agent-network
    volumes:
      - ./videos:/app/videos

networks:
  agent-network:
    name: agent-network

volumes:
  videos: