[project]
name = "ingestion"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ipykernel>=6.29.5",
    "openai-whisper",
    "pip>=25.0.1",
    "pixeltable>=0.3.10",
    "spacy>=3.8.5",
    "torch>=2.6.0",
    "transformers>=4.51.1",
    "yt-dlp>=2025.3.31",
]

[tool.uv.sources]
openai-whisper = { git = "https://github.com/openai/whisper.git" }
